name: Rust

on: [push]

jobs:
  job_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Check compilation
        uses: actions-rs/cargo@v1
        with:
          command: check

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/reddsaver
            asset_name: reddsaver-linux-amd64
          - name: windows
            os: windows-latest
            artifact_name: target/release/reddsaver.exe
            asset_name: reddsaver-windows-amd64
          - name: macos
            os: macos-latest
            artifact_name: target/release/reddsaver
            asset_name: reddsaver-macos-amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --locked

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
